sudo: required
dist: trusty
language: node_js
node_js:
- 7.0
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: fz1Z7aKZY7xsPkTI3TN3ajDLTf32WJ2ZJgNUUa1mWRn/pq3hbDTWGNNDT5zB5a5mn4EF0Iw6UgjNZJOyiVGyGH8/FIERjx8EQOvQXNM3rO7uvgDVP1VAXKuEKGTvhHCqhPCZQnTCnO99dbBkQdYziW7nhAVyxn7ZHFJC3PdRLucLSAQkokq8uLQmv3gtGAaTSZXL+EbxrIgRVQ31j0R8QFWQXa5X7tphW9h8MAO6+KPXrmuOhERN8tBiKsTpzE3UYz8HNZVa6jztvbbrj5UvjmCuu9Y6oooyrX6VtVKeB/SoDtMUwlx5S7h48wIA79j5WxAmOQkep7LAgBSRRQdfd05loduWlADRYy/tmdCRP48v+zHOgCcdBmSBZsYkZLzA7J0fcX3cO7TIgj8B27CgIgrvgOthNarXpUBkKlIKBTyDDClCnOctJbKDDRCAUQwTURhWrzR37eJaZu1VOdLGs008SO87d6KR8vwh1mDa8AK8vI5tfH60KCsflZASSLBS51gFzt6CO25zrCObhp/bZUegyjDX9TARcsXxpTEYneaIaoxnjjIiWTPH4mgdF6WlOdt2EKjIkiFqG/1AzD03mCj9U+4V2dvUE6MnaZZkle85bQzKKMRBHbXCN7387tJRqvL/GVZZcKBpCJZhb3OcT+3dA3H7L0/kjXgb98as5os=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install: 
script:
- npm test
after_script:
- sudo ./update-gh-pages.sh
