language: node_js
node_js:
  - 7.0
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
after_success:
  - bash <(curl -s https://codecov.io/bash)